.\" Man page for decode.c, a program in Lab 6 of CSCI 241
.\" Zac Plett and Ezra Goss - Fall 2017

.TH decode 1 "19 November 2017"	"CSCI 241" "Oberlin College"

.SH NAME
.B decode
\- A man page for decode.c

.SH DESCRIPTION
Decode takes in a file that represents a Huffman encoding and decodes the file.

.SH AUTHORS
Zac Plett and Ezra Goss	( Fall 2017 )

.SH BUGS
None!
