.\" Man page for encode.c, a program in Lab 6 of CSCI 241
.\" Zac Plett and Ezra Goss - Fall 2017

.TH encode 1 "19 November 2017" "CSCI 241" "Oberlin College"

.SH NAME
.B encode
\- A man page for encode.c

.SH DESCRIPTION
Encode takes in a file to be encoded using Huffman's algorithm and associate trees.

.SH AUTHORS
Zac Plett and Ezra Goss ( Fall 2017 )

.SH BUGS
None!
